package ru.sogya.projects.domovoy.models.mappers

import com.sogya.domain.models.AttributesDomain
import ru.sogya.projects.domovoy.models.AttributesPresentation

class AttributeMapper(
    private val attributesDomain: AttributesDomain?
) {
    fun map():AttributesPresentation = AttributesPresentation(
        attributesDomain?.nextDawn,
        attributesDomain?.nextDusk,
        attributesDomain?.nextMidnight,
        attributesDomain?.nextNoon,
        attributesDomain?.nextRising,
        attributesDomain?.nextSetting,
        attributesDomain?.fanSpeedList,
        attributesDomain?.speedList,
        attributesDomain?.assumedState,
        attributesDomain?.friendlyName,
        attributesDomain?.appName,
        attributesDomain?.isVolumeMuted,
        attributesDomain?.volumeLevel,
        attributesDomain?.entityPicture,
        attributesDomain?.icon,
        attributesDomain?.title,
        attributesDomain?.year,
        attributesDomain?.month,
        attributesDomain?.day,
        attributesDomain?.hour,
        attributesDomain?.minute,
        attributesDomain?.timestamp,
        attributesDomain?.hasDate,
        attributesDomain?.hasTime,
        attributesDomain?.deviceClass,
        attributesDomain?.brightness,
        attributesDomain?.colorTemp,
        attributesDomain?.rgbColors,
        attributesDomain?.options,
        attributesDomain?.order,
        attributesDomain?.auto,
        attributesDomain?.hidden,
        attributesDomain?.view,
        attributesDomain?.name,
        attributesDomain?.initial,
        attributesDomain?.codeFormat,
        attributesDomain?.pattern,
        attributesDomain?.max,
        attributesDomain?.min,
        attributesDomain?.step,
        attributesDomain?.currentTemperature,
        attributesDomain?.maxTemp,
        attributesDomain?.minTemp,
        attributesDomain?.temperature,
        attributesDomain?.operationMode,
        attributesDomain?.activity,
        attributesDomain?.provider,
        attributesDomain?.sourceType,
        attributesDomain?.battery,
        attributesDomain?.gpsAccuracy,
        attributesDomain?.altitude,
        attributesDomain?.latitude,
        attributesDomain?.longitude,
        attributesDomain?.radius,
        attributesDomain?.releaseNotes,
        attributesDomain?.unitOfMeasurement,
        attributesDomain?.mediaPlayerSongName,
        attributesDomain?.mediaPlayerArtistName,
        attributesDomain?.mediaDuration,
        attributesDomain?.mediaPosition,
        attributesDomain?.currentPosition
    )
}