package ru.sogya.projects.domovoy.models

import com.sogya.domain.models.AttributesDomain
import java.math.BigDecimal

data class AttributesPresentation(
    override var nextDawn: String?,
    override var nextDusk: String?,
    override var nextMidnight: String?,
    override var nextNoon: String?,
    override var nextRising: String?,
    override var nextSetting: String?,
    override var speedList: ArrayList<String>?,
    override var fanSpeedList: ArrayList<String>?,
    override var assumedState: String?,
    override var friendlyName: String?,
    override var appName: String?,
    override var isVolumeMuted: Boolean?,
    override var volumeLevel: Double?,
    override var entityPicture: String?,
    override var icon: String?,
    override var title: String?,
    override var year: Int?,
    override var month: Int?,
    override var day: Int?,
    override var hour: Int?,
    override var minute: Int?,
    override var timestamp: String?,
    override var hasDate: Boolean?,
    override var hasTime: Boolean?,
    override var deviceClass: String?,
    override var brightness: BigDecimal?,
    override var colorTemp: BigDecimal?,
    override var rgbColors: ArrayList<BigDecimal>?,
    override var options: ArrayList<String>?,
    override var order: Int?,
    override var auto: Boolean?,
    override var hidden: Boolean?,
    override var view: Boolean?,
    override var name: String?,
    override var initial: Int?,
    override var codeFormat: String?,
    override var pattern: String?,
    override var max: BigDecimal?,
    override var min: BigDecimal?,
    override var step: BigDecimal?,
    override var currentTemperature: BigDecimal?,
    override var maxTemp: BigDecimal?,
    override var minTemp: BigDecimal?,
    override var temperature: String?,
    override var operationMode: String?,
    override var activity: String?,
    override var provider: String?,
    override var sourceType: String?,
    override var battery: String?,
    override var gpsAccuracy: BigDecimal?,
    override var altitude: BigDecimal?,
    override var latitude: BigDecimal?,
    override var longitude: BigDecimal?,
    override var radius: BigDecimal?,
    override var releaseNotes: Boolean?,
    override var unitOfMeasurement: String?,
    override var mediaPlayerSongName: String?,
    override var mediaPlayerArtistName: String?,
    override var mediaDuration: Double?,
    override var mediaPosition: Double?,
    override var currentPosition: Int?
):AttributesDomain
